-- Seed public.subjects with the real Crescent School Upper School course
-- list, taken from the Crescent School Upper School course guide. This is a
-- one-time data seed, not a schema change -- the ON CONFLICT DO NOTHING
-- makes it safe to re-run. After this runs, admins manage the list going
-- forward from /admin/subjects (rename, deactivate, add new courses) rather
-- than through further seed migrations.

insert into public.subjects (name) values
  ('ADA1O - Drama (Grade 9)'),
  ('ADA2O - Drama (Grade 10)'),
  ('ADA3M - Drama (Grade 11)'),
  ('ADA4M - Drama (Grade 12)'),
  ('AMU1O - Music (Grade 9)'),
  ('AMU2O - Music (Grade 10)'),
  ('AMU3M - Music (Grade 11)'),
  ('AMU4M - Music (Grade 12)'),
  ('AVI1O - Visual Arts (Grade 9)'),
  ('AVI2O - Visual Arts (Grade 10)'),
  ('AVI3M - Visual Arts (Grade 11)'),
  ('AVI4M - Visual Arts (Grade 12)'),
  ('BAF3M - Financial Accounting Fundamentals (Grade 11)'),
  ('BAT4M - Financial Accounting Principles (Grade 12)'),
  ('BBB4M - International Business Fundamentals (Grade 12)'),
  ('CGC1W - Exploring Canadian Geography (Grade 9)'),
  ('CGF3M - Forces of Nature: Physical Processes and Disasters (Grade 11)'),
  ('CGR4M - The Environment and Resource Management (Grade 12)'),
  ('CGR4M1 - The Environment and Resource Management + AP Environmental Science (Grade 12)'),
  ('CGW4U1 - World Issues, A Geographic Analysis + AP Human Geography (Grade 12)'),
  ('CHA3U - American History (Grade 11)'),
  ('CHC2D - Canadian History since World War I (Grade 10)'),
  ('CHW3M - World History to the End of the 15th Century (Grade 11)'),
  ('CHY4U - World History since the 15th Century (Grade 12)'),
  ('CIA4U - Analyzing Current Economic Issues (Grade 12)'),
  ('CIA4U1 - Analyzing Current Economic Issues + AP Micro and Macroeconomics (Grade 12)'),
  ('CIE3M - The Individual and the Economy (Grade 11)'),
  ('CLN4U - Canadian and International Law (Grade 12)'),
  ('CLU3M - Understanding Canadian Law (Grade 11)'),
  ('CPW4U - Canadian and International Politics (Grade 12)'),
  ('ENG2D - English (Grade 10)'),
  ('ENG3U - English (Grade 11)'),
  ('ENG4U - English (Grade 12)'),
  ('ENG4U1 - English with AP English Literature and Composition (Grade 12)'),
  ('ENL1W - English (Grade 9)'),
  ('EWC4U - The Writer’s Craft (Grade 12)'),
  ('FSF1D - Core French (Grade 9)'),
  ('FSF2D - Core French (Grade 10)'),
  ('FSF2D1 - Enriched Core French (Grade 10)'),
  ('FSF3U - Core French (Grade 11)'),
  ('FSF3U1 - Enriched Core French (Grade 11)'),
  ('FSF4U - Core French (Grade 12)'),
  ('FSF4U1 - French + AP French Language and Culture (Grade 12)'),
  ('GLC2O - Career Studies (Grade 10)'),
  ('HSB4U - Challenge and Change in Society (Grade 12)'),
  ('HSB4U1 - AP Seminar (Grade 11)'),
  ('HSP3U - Introduction to Anthropology, Psychology and Sociology (Grade 11)'),
  ('HZT4U - Philosophy: Questions and Theories (Grade 12)'),
  ('ICS3U - Introduction to Computer Science (Grade 11)'),
  ('ICS4U - Computer Science (Grade 12)'),
  ('ICS4U1 - Computer Science + AP Computer Science A (Grade 12)'),
  ('IDC4U - Crescent Media Production (Grade 12)'),
  ('IDC4U1 - AP Research (Grade 12)'),
  ('MCF3M - Functions and Applications (Grade 11)'),
  ('MCR3U - Functions (Grade 11)'),
  ('MCR3U1 - Enriched Functions (Grade 11)'),
  ('MCV4U - Calculus and Vectors (Grade 12)'),
  ('MCV4U1 - Calculus + AP Calculus AB (Grade 12)'),
  ('MDM4U - Mathematics of Data Management (Grade 12)'),
  ('MDM4U1 - Mathematics of Data Management + AP Statistics (Grade 12)'),
  ('MHF4U - Advanced Functions (Grade 12)'),
  ('MPM2D - Principles of Mathematics (Grade 10)'),
  ('MPM2D1 - Enriched Principles of Mathematics (Grade 10)'),
  ('MTH1W - Mathematics (Grade 9)'),
  ('PAF3O - Personal and Fitness Activities (Grade 11)'),
  ('PPL1O - Healthy Active Living Education (Grade 9)'),
  ('PPL2O - Healthy Active Living Education (Grade 10)'),
  ('PSK4U - Introduction to Kinesiology (Grade 12)'),
  ('SBI3U - Biology (Grade 11)'),
  ('SBI4U - Biology (Grade 12)'),
  ('SBI4U1 - Biology + AP Biology (Grade 12)'),
  ('SCH3U - Chemistry (Grade 11)'),
  ('SCH4U - Chemistry (Grade 12)'),
  ('SCH4U1 - Chemistry + AP Chemistry (Grade 12)'),
  ('SES4U - Earth and Space Science (Grade 12)'),
  ('SNC1W - Science (Grade 9)'),
  ('SNC2D - Science (Grade 10)'),
  ('SPH3U - Physics (Grade 11)'),
  ('SPH4U - Physics (Grade 12)'),
  ('SPH4U1 - Physics + AP Physics 1 (Grade 12)'),
  ('TAS2O - Technology and the Skilled Trades (Grade 10)'),
  ('TDJ2O - Technological Design and the Skilled Trades (Grade 10)'),
  ('TDJ3M - Technological Design (Grade 11)'),
  ('TDJ4M - Technological Design (Grade 12)'),
  ('TGJ2O - Communications Technology and the Skilled Trades (Grade 10)'),
  ('TGJ3M - Communications Technology (Grade 11)'),
  ('TGJ4M - Communications Technology (Grade 12)')
on conflict (name) do nothing;
